services:
    app:
        # 실행 시킬 서버 코드, 다른 이름으로 지정해도 된다.
        build:
            # 빌드 명령을 실행할 디렉터리 경로
            context: .
            # 도커 이미지를 빌드하는데 사용할 도커 파일
            dockerfile: ./Dockerfile
        restart: always
        ports:
            - 3000:3000
        depends_on:
            # 의존 관계 설정
            - database

    database:
        # 'database'서비스에서 참조할 이미지
        image: mysql:8.0
        ports:
            - 3306:3306
        restart: always
        env_file:
            - './.env'
